
package jp.yahooapis.im.v201812.feeddata;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201812.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeedDataServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData")
@XmlSeeAlso({
    jp.yahooapis.im.v201812.ObjectFactory.class,
    jp.yahooapis.im.v201812.feeddata.ObjectFactory.class
})
public interface FeedDataServiceInterface {


    /**
     * 
     * @param accountId
     * @param itemListUploadType
     * @param rval
     * @param error
     * @param feedHolderId
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getUploadUrl", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", className = "jp.yahooapis.im.v201812.feeddata.GetUploadUrl")
    @ResponseWrapper(localName = "getUploadUrlResponse", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", className = "jp.yahooapis.im.v201812.feeddata.GetUploadUrlResponse")
    public void getUploadUrl(
        @WebParam(name = "accountId", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData")
        long accountId,
        @WebParam(name = "itemListUploadType", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData")
        ItemListUploadType itemListUploadType,
        @WebParam(name = "feedHolderId", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData")
        long feedHolderId,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", mode = WebParam.Mode.OUT)
        Holder<UploadUrlValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getUploadStatus", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", className = "jp.yahooapis.im.v201812.feeddata.GetUploadStatus")
    @ResponseWrapper(localName = "getUploadStatusResponse", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", className = "jp.yahooapis.im.v201812.feeddata.GetUploadStatusResponse")
    public void getUploadStatus(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData")
        FeedDataSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", mode = WebParam.Mode.OUT)
        Holder<FeedDataPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
