
package jp.yahooapis.im.v201812.feeddata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeedDataServiceService", targetNamespace = "http://im.yahooapis.jp/V201812/FeedData", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201812/FeedDataService?wsdl")
public class FeedDataServiceService
    extends Service
{

    private final static URL FEEDDATASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FEEDDATASERVICESERVICE_EXCEPTION;
    private final static QName FEEDDATASERVICESERVICE_QNAME = new QName("http://im.yahooapis.jp/V201812/FeedData", "FeedDataServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201812/FeedDataService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEEDDATASERVICESERVICE_WSDL_LOCATION = url;
        FEEDDATASERVICESERVICE_EXCEPTION = e;
    }

    public FeedDataServiceService() {
        super(__getWsdlLocation(), FEEDDATASERVICESERVICE_QNAME);
    }

    public FeedDataServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEEDDATASERVICESERVICE_QNAME, features);
    }

    public FeedDataServiceService(URL wsdlLocation) {
        super(wsdlLocation, FEEDDATASERVICESERVICE_QNAME);
    }

    public FeedDataServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEEDDATASERVICESERVICE_QNAME, features);
    }

    public FeedDataServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeedDataServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeedDataServiceInterface
     */
    @WebEndpoint(name = "FeedDataService")
    public FeedDataServiceInterface getFeedDataService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201812/FeedData", "FeedDataService"), FeedDataServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeedDataServiceInterface
     */
    @WebEndpoint(name = "FeedDataService")
    public FeedDataServiceInterface getFeedDataService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201812/FeedData", "FeedDataService"), FeedDataServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEEDDATASERVICESERVICE_EXCEPTION!= null) {
            throw FEEDDATASERVICESERVICE_EXCEPTION;
        }
        return FEEDDATASERVICESERVICE_WSDL_LOCATION;
    }

}
