
package jp.yahooapis.im.v201806.adgrouptarget;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201806.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdGroupTargetServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget")
@XmlSeeAlso({
    jp.yahooapis.im.v201806.ObjectFactory.class,
    jp.yahooapis.im.v201806.adgrouptarget.ObjectFactory.class
})
public interface AdGroupTargetServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", className = "jp.yahooapis.im.v201806.adgrouptarget.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", className = "jp.yahooapis.im.v201806.adgrouptarget.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget")
        AdGroupTargetSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", mode = WebParam.Mode.OUT)
        Holder<AdGroupTargetPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", className = "jp.yahooapis.im.v201806.adgrouptarget.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", className = "jp.yahooapis.im.v201806.adgrouptarget.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget")
        AdGroupTargetMutateOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", mode = WebParam.Mode.OUT)
        Holder<AdGroupTargetReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "replace", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", className = "jp.yahooapis.im.v201806.adgrouptarget.Replace")
    @ResponseWrapper(localName = "replaceResponse", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", className = "jp.yahooapis.im.v201806.adgrouptarget.ReplaceResponse")
    public void replace(
        @WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget")
        AdGroupTargetOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", mode = WebParam.Mode.OUT)
        Holder<AdGroupTargetReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201806/AdGroupTarget", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
