
package jp.yahooapis.im.v201911.feedftprequest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeedFtpRequestService", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtpRequest", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201911/FeedFtpRequestService?wsdl")
public class FeedFtpRequestService
    extends Service
{

    private final static URL FEEDFTPREQUESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FEEDFTPREQUESTSERVICE_EXCEPTION;
    private final static QName FEEDFTPREQUESTSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201911/FeedFtpRequest", "FeedFtpRequestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201911/FeedFtpRequestService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEEDFTPREQUESTSERVICE_WSDL_LOCATION = url;
        FEEDFTPREQUESTSERVICE_EXCEPTION = e;
    }

    public FeedFtpRequestService() {
        super(__getWsdlLocation(), FEEDFTPREQUESTSERVICE_QNAME);
    }

    public FeedFtpRequestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEEDFTPREQUESTSERVICE_QNAME, features);
    }

    public FeedFtpRequestService(URL wsdlLocation) {
        super(wsdlLocation, FEEDFTPREQUESTSERVICE_QNAME);
    }

    public FeedFtpRequestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEEDFTPREQUESTSERVICE_QNAME, features);
    }

    public FeedFtpRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeedFtpRequestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeedFtpRequestServiceInterface
     */
    @WebEndpoint(name = "FeedFtpRequestService")
    public FeedFtpRequestServiceInterface getFeedFtpRequestService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201911/FeedFtpRequest", "FeedFtpRequestService"), FeedFtpRequestServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeedFtpRequestServiceInterface
     */
    @WebEndpoint(name = "FeedFtpRequestService")
    public FeedFtpRequestServiceInterface getFeedFtpRequestService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201911/FeedFtpRequest", "FeedFtpRequestService"), FeedFtpRequestServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEEDFTPREQUESTSERVICE_EXCEPTION!= null) {
            throw FEEDFTPREQUESTSERVICE_EXCEPTION;
        }
        return FEEDFTPREQUESTSERVICE_WSDL_LOCATION;
    }

}
