
package jp.yahooapis.im.v201812.adgrouptarget;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdGroupTargetServiceService", targetNamespace = "http://im.yahooapis.jp/V201812/AdGroupTarget", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201812/AdGroupTargetService?wsdl")
public class AdGroupTargetServiceService
    extends Service
{

    private final static URL ADGROUPTARGETSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADGROUPTARGETSERVICESERVICE_EXCEPTION;
    private final static QName ADGROUPTARGETSERVICESERVICE_QNAME = new QName("http://im.yahooapis.jp/V201812/AdGroupTarget", "AdGroupTargetServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201812/AdGroupTargetService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADGROUPTARGETSERVICESERVICE_WSDL_LOCATION = url;
        ADGROUPTARGETSERVICESERVICE_EXCEPTION = e;
    }

    public AdGroupTargetServiceService() {
        super(__getWsdlLocation(), ADGROUPTARGETSERVICESERVICE_QNAME);
    }

    public AdGroupTargetServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADGROUPTARGETSERVICESERVICE_QNAME, features);
    }

    public AdGroupTargetServiceService(URL wsdlLocation) {
        super(wsdlLocation, ADGROUPTARGETSERVICESERVICE_QNAME);
    }

    public AdGroupTargetServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADGROUPTARGETSERVICESERVICE_QNAME, features);
    }

    public AdGroupTargetServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupTargetServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdGroupTargetServiceInterface
     */
    @WebEndpoint(name = "AdGroupTargetService")
    public AdGroupTargetServiceInterface getAdGroupTargetService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201812/AdGroupTarget", "AdGroupTargetService"), AdGroupTargetServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupTargetServiceInterface
     */
    @WebEndpoint(name = "AdGroupTargetService")
    public AdGroupTargetServiceInterface getAdGroupTargetService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201812/AdGroupTarget", "AdGroupTargetService"), AdGroupTargetServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADGROUPTARGETSERVICESERVICE_EXCEPTION!= null) {
            throw ADGROUPTARGETSERVICESERVICE_EXCEPTION;
        }
        return ADGROUPTARGETSERVICESERVICE_WSDL_LOCATION;
    }

}
