
package jp.yahooapis.im.v201812.feedholder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeedHolderServiceService", targetNamespace = "http://im.yahooapis.jp/V201812/FeedHolder", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201812/FeedHolderService?wsdl")
public class FeedHolderServiceService
    extends Service
{

    private final static URL FEEDHOLDERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FEEDHOLDERSERVICESERVICE_EXCEPTION;
    private final static QName FEEDHOLDERSERVICESERVICE_QNAME = new QName("http://im.yahooapis.jp/V201812/FeedHolder", "FeedHolderServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201812/FeedHolderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEEDHOLDERSERVICESERVICE_WSDL_LOCATION = url;
        FEEDHOLDERSERVICESERVICE_EXCEPTION = e;
    }

    public FeedHolderServiceService() {
        super(__getWsdlLocation(), FEEDHOLDERSERVICESERVICE_QNAME);
    }

    public FeedHolderServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEEDHOLDERSERVICESERVICE_QNAME, features);
    }

    public FeedHolderServiceService(URL wsdlLocation) {
        super(wsdlLocation, FEEDHOLDERSERVICESERVICE_QNAME);
    }

    public FeedHolderServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEEDHOLDERSERVICESERVICE_QNAME, features);
    }

    public FeedHolderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeedHolderServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeedHolderServiceInterface
     */
    @WebEndpoint(name = "FeedHolderService")
    public FeedHolderServiceInterface getFeedHolderService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201812/FeedHolder", "FeedHolderService"), FeedHolderServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeedHolderServiceInterface
     */
    @WebEndpoint(name = "FeedHolderService")
    public FeedHolderServiceInterface getFeedHolderService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201812/FeedHolder", "FeedHolderService"), FeedHolderServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEEDHOLDERSERVICESERVICE_EXCEPTION!= null) {
            throw FEEDHOLDERSERVICESERVICE_EXCEPTION;
        }
        return FEEDHOLDERSERVICESERVICE_WSDL_LOCATION;
    }

}
