
package jp.yahooapis.im.v201911.feedftp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201911.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeedFtpServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp")
@XmlSeeAlso({
    jp.yahooapis.im.v201911.ObjectFactory.class,
    jp.yahooapis.im.v201911.feedftp.ObjectFactory.class
})
public interface FeedFtpServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", className = "jp.yahooapis.im.v201911.feedftp.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", className = "jp.yahooapis.im.v201911.feedftp.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp")
        FeedFtpSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", mode = WebParam.Mode.OUT)
        Holder<FeedFtpPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", className = "jp.yahooapis.im.v201911.feedftp.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", className = "jp.yahooapis.im.v201911.feedftp.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp")
        FeedFtpOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", mode = WebParam.Mode.OUT)
        Holder<FeedFtpReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201911/FeedFtp", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
