
package jp.yahooapis.im.v201903.reportdefinition;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201903.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportDefinitionServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition")
@XmlSeeAlso({
    jp.yahooapis.im.v201903.ObjectFactory.class,
    jp.yahooapis.im.v201903.reportdefinition.ObjectFactory.class
})
public interface ReportDefinitionServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", className = "jp.yahooapis.im.v201903.reportdefinition.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", className = "jp.yahooapis.im.v201903.reportdefinition.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition")
        ReportDefinitionSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", mode = WebParam.Mode.OUT)
        Holder<ReportDefinitionPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", className = "jp.yahooapis.im.v201903.reportdefinition.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", className = "jp.yahooapis.im.v201903.reportdefinition.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition")
        ReportDefinitionOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", mode = WebParam.Mode.OUT)
        Holder<ReportDefinitionReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param reportCategory
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getReportFields", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", className = "jp.yahooapis.im.v201903.reportdefinition.GetReportFields")
    @ResponseWrapper(localName = "getReportFieldsResponse", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", className = "jp.yahooapis.im.v201903.reportdefinition.GetReportFieldsResponse")
    public void getReportFields(
        @WebParam(name = "reportCategory", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition")
        ReportCategory reportCategory,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", mode = WebParam.Mode.OUT)
        Holder<ReportDefinitionFieldValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201903/ReportDefinition", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
