
package jp.yahooapis.im.v201812.stats;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201812.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatsServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201812/Stats")
@XmlSeeAlso({
    jp.yahooapis.im.v201812.ObjectFactory.class,
    jp.yahooapis.im.v201812.stats.ObjectFactory.class
})
public interface StatsServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201812/Stats", className = "jp.yahooapis.im.v201812.stats.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201812/Stats", className = "jp.yahooapis.im.v201812.stats.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201812/Stats")
        StatsSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201812/Stats", mode = WebParam.Mode.OUT)
        Holder<StatsPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201812/Stats", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
