
package jp.yahooapis.im.v201903.promotionalaccount;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PromotionalAccountService", targetNamespace = "http://im.yahooapis.jp/V201903/PromotionalAccount", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201903/PromotionalAccountService?wsdl")
public class PromotionalAccountService
    extends Service
{

    private final static URL PROMOTIONALACCOUNTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROMOTIONALACCOUNTSERVICE_EXCEPTION;
    private final static QName PROMOTIONALACCOUNTSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201903/PromotionalAccount", "PromotionalAccountService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201903/PromotionalAccountService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROMOTIONALACCOUNTSERVICE_WSDL_LOCATION = url;
        PROMOTIONALACCOUNTSERVICE_EXCEPTION = e;
    }

    public PromotionalAccountService() {
        super(__getWsdlLocation(), PROMOTIONALACCOUNTSERVICE_QNAME);
    }

    public PromotionalAccountService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROMOTIONALACCOUNTSERVICE_QNAME, features);
    }

    public PromotionalAccountService(URL wsdlLocation) {
        super(wsdlLocation, PROMOTIONALACCOUNTSERVICE_QNAME);
    }

    public PromotionalAccountService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROMOTIONALACCOUNTSERVICE_QNAME, features);
    }

    public PromotionalAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PromotionalAccountService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PromotionalAccountServiceInterface
     */
    @WebEndpoint(name = "PromotionalAccountService")
    public PromotionalAccountServiceInterface getPromotionalAccountService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/PromotionalAccount", "PromotionalAccountService"), PromotionalAccountServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PromotionalAccountServiceInterface
     */
    @WebEndpoint(name = "PromotionalAccountService")
    public PromotionalAccountServiceInterface getPromotionalAccountService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/PromotionalAccount", "PromotionalAccountService"), PromotionalAccountServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROMOTIONALACCOUNTSERVICE_EXCEPTION!= null) {
            throw PROMOTIONALACCOUNTSERVICE_EXCEPTION;
        }
        return PROMOTIONALACCOUNTSERVICE_WSDL_LOCATION;
    }

}
