
package jp.yahooapis.im.V6.CampaignService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CampaignServiceService", targetNamespace = "http://im.yahooapis.jp/V6", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V6.1/CampaignService?wsdl")
public class CampaignServiceService
    extends Service
{

    private final static URL CAMPAIGNSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CAMPAIGNSERVICESERVICE_EXCEPTION;
    private final static QName CAMPAIGNSERVICESERVICE_QNAME = new QName("http://im.yahooapis.jp/V6", "CampaignServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V6.1/CampaignService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAMPAIGNSERVICESERVICE_WSDL_LOCATION = url;
        CAMPAIGNSERVICESERVICE_EXCEPTION = e;
    }

    public CampaignServiceService() {
        super(__getWsdlLocation(), CAMPAIGNSERVICESERVICE_QNAME);
    }

    public CampaignServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAMPAIGNSERVICESERVICE_QNAME, features);
    }

    public CampaignServiceService(URL wsdlLocation) {
        super(wsdlLocation, CAMPAIGNSERVICESERVICE_QNAME);
    }

    public CampaignServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAMPAIGNSERVICESERVICE_QNAME, features);
    }

    public CampaignServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampaignServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CampaignServiceInterface
     */
    @WebEndpoint(name = "CampaignService")
    public CampaignServiceInterface getCampaignService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V6", "CampaignService"), CampaignServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CampaignServiceInterface
     */
    @WebEndpoint(name = "CampaignService")
    public CampaignServiceInterface getCampaignService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V6", "CampaignService"), CampaignServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAMPAIGNSERVICESERVICE_EXCEPTION!= null) {
            throw CAMPAIGNSERVICESERVICE_EXCEPTION;
        }
        return CAMPAIGNSERVICESERVICE_WSDL_LOCATION;
    }

}
