
package jp.yahooapis.im.v201809.bulk;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201809.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BulkServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk")
@XmlSeeAlso({
    jp.yahooapis.im.v201809.ObjectFactory.class,
    jp.yahooapis.im.v201809.bulk.ObjectFactory.class
})
public interface BulkServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getBulkDownload", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetBulkDownload")
    @ResponseWrapper(localName = "getBulkDownloadResponse", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetBulkDownloadResponse")
    public void getBulkDownload(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk")
        BulkDownloadSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<BulkDownloadReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getBulkDownloadStatus", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetBulkDownloadStatus")
    @ResponseWrapper(localName = "getBulkDownloadStatusResponse", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetBulkDownloadStatusResponse")
    public void getBulkDownloadStatus(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk")
        BulkDownloadStatusSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<BulkDownloadStatusPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param accountId
     * @param uploadBulkJobName
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getUploadUrl", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetUploadUrl")
    @ResponseWrapper(localName = "getUploadUrlResponse", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetUploadUrlResponse")
    public void getUploadUrl(
        @WebParam(name = "accountId", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk")
        long accountId,
        @WebParam(name = "uploadBulkJobName", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk")
        String uploadBulkJobName,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<UploadUrlValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getBulkUploadStatus", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetBulkUploadStatus")
    @ResponseWrapper(localName = "getBulkUploadStatusResponse", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", className = "jp.yahooapis.im.v201809.bulk.GetBulkUploadStatusResponse")
    public void getBulkUploadStatus(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk")
        BulkUploadStatusSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<BulkUploadStatusPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201809/Bulk", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
