
package jp.yahooapis.im.v201806.searchkeywordidea;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchKeywordIdeaService", targetNamespace = "http://im.yahooapis.jp/V201806/SearchKeywordIdea", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201806/SearchKeywordIdeaService?wsdl")
public class SearchKeywordIdeaService
    extends Service
{

    private final static URL SEARCHKEYWORDIDEASERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHKEYWORDIDEASERVICE_EXCEPTION;
    private final static QName SEARCHKEYWORDIDEASERVICE_QNAME = new QName("http://im.yahooapis.jp/V201806/SearchKeywordIdea", "SearchKeywordIdeaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201806/SearchKeywordIdeaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHKEYWORDIDEASERVICE_WSDL_LOCATION = url;
        SEARCHKEYWORDIDEASERVICE_EXCEPTION = e;
    }

    public SearchKeywordIdeaService() {
        super(__getWsdlLocation(), SEARCHKEYWORDIDEASERVICE_QNAME);
    }

    public SearchKeywordIdeaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHKEYWORDIDEASERVICE_QNAME, features);
    }

    public SearchKeywordIdeaService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHKEYWORDIDEASERVICE_QNAME);
    }

    public SearchKeywordIdeaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHKEYWORDIDEASERVICE_QNAME, features);
    }

    public SearchKeywordIdeaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchKeywordIdeaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchKeywordIdeaServiceInterface
     */
    @WebEndpoint(name = "SearchKeywordIdeaService")
    public SearchKeywordIdeaServiceInterface getSearchKeywordIdeaService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201806/SearchKeywordIdea", "SearchKeywordIdeaService"), SearchKeywordIdeaServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchKeywordIdeaServiceInterface
     */
    @WebEndpoint(name = "SearchKeywordIdeaService")
    public SearchKeywordIdeaServiceInterface getSearchKeywordIdeaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201806/SearchKeywordIdea", "SearchKeywordIdeaService"), SearchKeywordIdeaServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHKEYWORDIDEASERVICE_EXCEPTION!= null) {
            throw SEARCHKEYWORDIDEASERVICE_EXCEPTION;
        }
        return SEARCHKEYWORDIDEASERVICE_WSDL_LOCATION;
    }

}
