
package jp.yahooapis.im.v201907.feedset;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeedSetService", targetNamespace = "http://im.yahooapis.jp/V201907/FeedSet", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201907/FeedSetService?wsdl")
public class FeedSetService
    extends Service
{

    private final static URL FEEDSETSERVICE_WSDL_LOCATION;
    private final static WebServiceException FEEDSETSERVICE_EXCEPTION;
    private final static QName FEEDSETSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201907/FeedSet", "FeedSetService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201907/FeedSetService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEEDSETSERVICE_WSDL_LOCATION = url;
        FEEDSETSERVICE_EXCEPTION = e;
    }

    public FeedSetService() {
        super(__getWsdlLocation(), FEEDSETSERVICE_QNAME);
    }

    public FeedSetService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEEDSETSERVICE_QNAME, features);
    }

    public FeedSetService(URL wsdlLocation) {
        super(wsdlLocation, FEEDSETSERVICE_QNAME);
    }

    public FeedSetService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEEDSETSERVICE_QNAME, features);
    }

    public FeedSetService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeedSetService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeedSetServiceInterface
     */
    @WebEndpoint(name = "FeedSetService")
    public FeedSetServiceInterface getFeedSetService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201907/FeedSet", "FeedSetService"), FeedSetServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeedSetServiceInterface
     */
    @WebEndpoint(name = "FeedSetService")
    public FeedSetServiceInterface getFeedSetService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201907/FeedSet", "FeedSetService"), FeedSetServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEEDSETSERVICE_EXCEPTION!= null) {
            throw FEEDSETSERVICE_EXCEPTION;
        }
        return FEEDSETSERVICE_WSDL_LOCATION;
    }

}
