
package jp.yahooapis.im.v201911.retargetingtag;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201911.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RetargetingTagServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag")
@XmlSeeAlso({
    jp.yahooapis.im.v201911.ObjectFactory.class,
    jp.yahooapis.im.v201911.retargetingtag.ObjectFactory.class
})
public interface RetargetingTagServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", className = "jp.yahooapis.im.v201911.retargetingtag.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", className = "jp.yahooapis.im.v201911.retargetingtag.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag")
        RetargetingTagSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", mode = WebParam.Mode.OUT)
        Holder<RetargetingTagPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", className = "jp.yahooapis.im.v201911.retargetingtag.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", className = "jp.yahooapis.im.v201911.retargetingtag.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag")
        RetargetingTagOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", mode = WebParam.Mode.OUT)
        Holder<RetargetingTagReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201911/RetargetingTag", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
