
package jp.yahooapis.im.v201911.searchkeywordlist;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201911.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchKeywordListServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList")
@XmlSeeAlso({
    jp.yahooapis.im.v201911.ObjectFactory.class,
    jp.yahooapis.im.v201911.searchkeywordlist.ObjectFactory.class
})
public interface SearchKeywordListServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", className = "jp.yahooapis.im.v201911.searchkeywordlist.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", className = "jp.yahooapis.im.v201911.searchkeywordlist.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList")
        SearchKeywordListSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", mode = WebParam.Mode.OUT)
        Holder<SearchKeywordListPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", className = "jp.yahooapis.im.v201911.searchkeywordlist.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", className = "jp.yahooapis.im.v201911.searchkeywordlist.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList")
        SearchKeywordListOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", mode = WebParam.Mode.OUT)
        Holder<SearchKeywordListReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
