
package jp.yahooapis.im.v201911.searchkeywordlist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchKeywordListService", targetNamespace = "http://im.yahooapis.jp/V201911/SearchKeywordList", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201911/SearchKeywordListService?wsdl")
public class SearchKeywordListService
    extends Service
{

    private final static URL SEARCHKEYWORDLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHKEYWORDLISTSERVICE_EXCEPTION;
    private final static QName SEARCHKEYWORDLISTSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201911/SearchKeywordList", "SearchKeywordListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201911/SearchKeywordListService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHKEYWORDLISTSERVICE_WSDL_LOCATION = url;
        SEARCHKEYWORDLISTSERVICE_EXCEPTION = e;
    }

    public SearchKeywordListService() {
        super(__getWsdlLocation(), SEARCHKEYWORDLISTSERVICE_QNAME);
    }

    public SearchKeywordListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHKEYWORDLISTSERVICE_QNAME, features);
    }

    public SearchKeywordListService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHKEYWORDLISTSERVICE_QNAME);
    }

    public SearchKeywordListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHKEYWORDLISTSERVICE_QNAME, features);
    }

    public SearchKeywordListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchKeywordListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchKeywordListServiceInterface
     */
    @WebEndpoint(name = "SearchKeywordListService")
    public SearchKeywordListServiceInterface getSearchKeywordListService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201911/SearchKeywordList", "SearchKeywordListService"), SearchKeywordListServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchKeywordListServiceInterface
     */
    @WebEndpoint(name = "SearchKeywordListService")
    public SearchKeywordListServiceInterface getSearchKeywordListService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201911/SearchKeywordList", "SearchKeywordListService"), SearchKeywordListServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHKEYWORDLISTSERVICE_EXCEPTION!= null) {
            throw SEARCHKEYWORDLISTSERVICE_EXCEPTION;
        }
        return SEARCHKEYWORDLISTSERVICE_WSDL_LOCATION;
    }

}
