
package jp.yahooapis.im.V6.AccountAdProductService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountAdProductService", targetNamespace = "http://im.yahooapis.jp/V6", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V6.1/AccountAdProductService?wsdl")
public class AccountAdProductService
    extends Service
{

    private final static URL ACCOUNTADPRODUCTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTADPRODUCTSERVICE_EXCEPTION;
    private final static QName ACCOUNTADPRODUCTSERVICE_QNAME = new QName("http://im.yahooapis.jp/V6", "AccountAdProductService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V6.1/AccountAdProductService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTADPRODUCTSERVICE_WSDL_LOCATION = url;
        ACCOUNTADPRODUCTSERVICE_EXCEPTION = e;
    }

    public AccountAdProductService() {
        super(__getWsdlLocation(), ACCOUNTADPRODUCTSERVICE_QNAME);
    }

    public AccountAdProductService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTADPRODUCTSERVICE_QNAME, features);
    }

    public AccountAdProductService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTADPRODUCTSERVICE_QNAME);
    }

    public AccountAdProductService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTADPRODUCTSERVICE_QNAME, features);
    }

    public AccountAdProductService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountAdProductService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountAdProductServiceInterface
     */
    @WebEndpoint(name = "AccountAdProductService")
    public AccountAdProductServiceInterface getAccountAdProductService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V6", "AccountAdProductService"), AccountAdProductServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountAdProductServiceInterface
     */
    @WebEndpoint(name = "AccountAdProductService")
    public AccountAdProductServiceInterface getAccountAdProductService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V6", "AccountAdProductService"), AccountAdProductServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTADPRODUCTSERVICE_EXCEPTION!= null) {
            throw ACCOUNTADPRODUCTSERVICE_EXCEPTION;
        }
        return ACCOUNTADPRODUCTSERVICE_WSDL_LOCATION;
    }

}
