
package jp.yahooapis.im.v201812.location;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201812.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocationServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201812/Location")
@XmlSeeAlso({
    jp.yahooapis.im.v201812.ObjectFactory.class,
    jp.yahooapis.im.v201812.location.ObjectFactory.class
})
public interface LocationServiceInterface {


    /**
     * 
     * @param accountId
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201812/Location", className = "jp.yahooapis.im.v201812.location.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201812/Location", className = "jp.yahooapis.im.v201812.location.GetResponse")
    public void get(
        @WebParam(name = "accountId", targetNamespace = "http://im.yahooapis.jp/V201812/Location")
        long accountId,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201812/Location", mode = WebParam.Mode.OUT)
        Holder<LocationReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201812/Location", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
