
package jp.yahooapis.im.V6.MediaService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MediaServiceService", targetNamespace = "http://im.yahooapis.jp/V6", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V6.1/MediaService?wsdl")
public class MediaServiceService
    extends Service
{

    private final static URL MEDIASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDIASERVICESERVICE_EXCEPTION;
    private final static QName MEDIASERVICESERVICE_QNAME = new QName("http://im.yahooapis.jp/V6", "MediaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V6.1/MediaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDIASERVICESERVICE_WSDL_LOCATION = url;
        MEDIASERVICESERVICE_EXCEPTION = e;
    }

    public MediaServiceService() {
        super(__getWsdlLocation(), MEDIASERVICESERVICE_QNAME);
    }

    public MediaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDIASERVICESERVICE_QNAME, features);
    }

    public MediaServiceService(URL wsdlLocation) {
        super(wsdlLocation, MEDIASERVICESERVICE_QNAME);
    }

    public MediaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDIASERVICESERVICE_QNAME, features);
    }

    public MediaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MediaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MediaServiceInterface
     */
    @WebEndpoint(name = "MediaService")
    public MediaServiceInterface getMediaService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V6", "MediaService"), MediaServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MediaServiceInterface
     */
    @WebEndpoint(name = "MediaService")
    public MediaServiceInterface getMediaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V6", "MediaService"), MediaServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDIASERVICESERVICE_EXCEPTION!= null) {
            throw MEDIASERVICESERVICE_EXCEPTION;
        }
        return MEDIASERVICESERVICE_WSDL_LOCATION;
    }

}
