
package jp.yahooapis.im.v201907.reportdefinition;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201907.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportDefinitionServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition")
@XmlSeeAlso({
    jp.yahooapis.im.v201907.ObjectFactory.class,
    ObjectFactory.class
})
public interface ReportDefinitionServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.GetResponse")
    public void get(@WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition") ReportDefinitionSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<ReportDefinitionPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.MutateResponse")
    public void mutate(@WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition") ReportDefinitionOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<ReportDefinitionReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param reportCategory
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getReportFields", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.GetReportFields")
    @ResponseWrapper(localName = "getReportFieldsResponse", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.GetReportFieldsResponse")
    public void getReportFields(@WebParam(name = "reportCategory", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition") ReportType reportCategory,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<ReportDefinitionFieldValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getClosedDate", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.GetClosedDate")
    @ResponseWrapper(localName = "getClosedDateResponse", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", className = "jp.yahooapis.im.v201907.reportdefinition.GetClosedDateResponse")
    public void getClosedDate(@WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition") ReportClosedDateSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<ReportClosedDateValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201907/ReportDefinition", mode = WebParam.Mode.OUT) Holder<List<Error>> error)
        throws ApiException
    ;

}
