
package jp.yahooapis.im.v201903.adgrouptarget;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdGroupTargetService", targetNamespace = "http://im.yahooapis.jp/V201903/AdGroupTarget", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201903/AdGroupTargetService?wsdl")
public class AdGroupTargetService
    extends Service
{

    private final static URL ADGROUPTARGETSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADGROUPTARGETSERVICE_EXCEPTION;
    private final static QName ADGROUPTARGETSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201903/AdGroupTarget", "AdGroupTargetService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201903/AdGroupTargetService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADGROUPTARGETSERVICE_WSDL_LOCATION = url;
        ADGROUPTARGETSERVICE_EXCEPTION = e;
    }

    public AdGroupTargetService() {
        super(__getWsdlLocation(), ADGROUPTARGETSERVICE_QNAME);
    }

    public AdGroupTargetService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADGROUPTARGETSERVICE_QNAME, features);
    }

    public AdGroupTargetService(URL wsdlLocation) {
        super(wsdlLocation, ADGROUPTARGETSERVICE_QNAME);
    }

    public AdGroupTargetService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADGROUPTARGETSERVICE_QNAME, features);
    }

    public AdGroupTargetService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupTargetService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdGroupTargetServiceInterface
     */
    @WebEndpoint(name = "AdGroupTargetService")
    public AdGroupTargetServiceInterface getAdGroupTargetService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/AdGroupTarget", "AdGroupTargetService"), AdGroupTargetServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupTargetServiceInterface
     */
    @WebEndpoint(name = "AdGroupTargetService")
    public AdGroupTargetServiceInterface getAdGroupTargetService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/AdGroupTarget", "AdGroupTargetService"), AdGroupTargetServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADGROUPTARGETSERVICE_EXCEPTION!= null) {
            throw ADGROUPTARGETSERVICE_EXCEPTION;
        }
        return ADGROUPTARGETSERVICE_WSDL_LOCATION;
    }

}
