
package jp.yahooapis.im.V6.BulkService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BulkServiceInterface", targetNamespace = "http://im.yahooapis.jp/V6")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BulkServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getBulkDownload", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetBulkDownload")
    @ResponseWrapper(localName = "getBulkDownloadResponse", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetBulkDownloadResponse")
    public void getBulkDownload(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V6")
        BulkDownloadSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<BulkDownloadReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getBulkDownloadStatus", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetBulkDownloadStatus")
    @ResponseWrapper(localName = "getBulkDownloadStatusResponse", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetBulkDownloadStatusResponse")
    public void getBulkDownloadStatus(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V6")
        BulkDownloadStatusSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<BulkDownloadStatusPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param accountId
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getUploadUrl", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetUploadUrl")
    @ResponseWrapper(localName = "getUploadUrlResponse", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetUploadUrlResponse")
    public void getUploadUrl(
        @WebParam(name = "accountId", targetNamespace = "http://im.yahooapis.jp/V6")
        long accountId,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<UploadUrlValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getBulkUploadStatus", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetBulkUploadStatus")
    @ResponseWrapper(localName = "getBulkUploadStatusResponse", targetNamespace = "http://im.yahooapis.jp/V6", className = "jp.yahooapis.im.V6.BulkService.GetBulkUploadStatusResponse")
    public void getBulkUploadStatus(
        @WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V6")
        BulkUploadStatusSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<BulkUploadStatusPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V6", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
