
package jp.yahooapis.im.v201903.placementurllist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlacementUrlListService", targetNamespace = "http://im.yahooapis.jp/V201903/PlacementUrlList", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201903/PlacementUrlListService?wsdl")
public class PlacementUrlListService
    extends Service
{

    private final static URL PLACEMENTURLLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLACEMENTURLLISTSERVICE_EXCEPTION;
    private final static QName PLACEMENTURLLISTSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201903/PlacementUrlList", "PlacementUrlListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201903/PlacementUrlListService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLACEMENTURLLISTSERVICE_WSDL_LOCATION = url;
        PLACEMENTURLLISTSERVICE_EXCEPTION = e;
    }

    public PlacementUrlListService() {
        super(__getWsdlLocation(), PLACEMENTURLLISTSERVICE_QNAME);
    }

    public PlacementUrlListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLACEMENTURLLISTSERVICE_QNAME, features);
    }

    public PlacementUrlListService(URL wsdlLocation) {
        super(wsdlLocation, PLACEMENTURLLISTSERVICE_QNAME);
    }

    public PlacementUrlListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLACEMENTURLLISTSERVICE_QNAME, features);
    }

    public PlacementUrlListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlacementUrlListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlacementUrlListServiceInterface
     */
    @WebEndpoint(name = "PlacementUrlListService")
    public PlacementUrlListServiceInterface getPlacementUrlListService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/PlacementUrlList", "PlacementUrlListService"), PlacementUrlListServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlacementUrlListServiceInterface
     */
    @WebEndpoint(name = "PlacementUrlListService")
    public PlacementUrlListServiceInterface getPlacementUrlListService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/PlacementUrlList", "PlacementUrlListService"), PlacementUrlListServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLACEMENTURLLISTSERVICE_EXCEPTION!= null) {
            throw PLACEMENTURLLISTSERVICE_EXCEPTION;
        }
        return PLACEMENTURLLISTSERVICE_WSDL_LOCATION;
    }

}
