
package jp.yahooapis.im.v201903.feedftp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeedFtpService", targetNamespace = "http://im.yahooapis.jp/V201903/FeedFtp", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201903/FeedFtpService?wsdl")
public class FeedFtpService
    extends Service
{

    private final static URL FEEDFTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FEEDFTPSERVICE_EXCEPTION;
    private final static QName FEEDFTPSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201903/FeedFtp", "FeedFtpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201903/FeedFtpService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEEDFTPSERVICE_WSDL_LOCATION = url;
        FEEDFTPSERVICE_EXCEPTION = e;
    }

    public FeedFtpService() {
        super(__getWsdlLocation(), FEEDFTPSERVICE_QNAME);
    }

    public FeedFtpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEEDFTPSERVICE_QNAME, features);
    }

    public FeedFtpService(URL wsdlLocation) {
        super(wsdlLocation, FEEDFTPSERVICE_QNAME);
    }

    public FeedFtpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEEDFTPSERVICE_QNAME, features);
    }

    public FeedFtpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeedFtpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeedFtpServiceInterface
     */
    @WebEndpoint(name = "FeedFtpService")
    public FeedFtpServiceInterface getFeedFtpService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/FeedFtp", "FeedFtpService"), FeedFtpServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeedFtpServiceInterface
     */
    @WebEndpoint(name = "FeedFtpService")
    public FeedFtpServiceInterface getFeedFtpService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201903/FeedFtp", "FeedFtpService"), FeedFtpServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEEDFTPSERVICE_EXCEPTION!= null) {
            throw FEEDFTPSERVICE_EXCEPTION;
        }
        return FEEDFTPSERVICE_WSDL_LOCATION;
    }

}
