
package jp.yahooapis.im.v201907.media;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.im.v201907.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MediaServiceInterface", targetNamespace = "http://im.yahooapis.jp/V201907/Media")
@XmlSeeAlso({
    jp.yahooapis.im.v201907.ObjectFactory.class,
    ObjectFactory.class
})
public interface MediaServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://im.yahooapis.jp/V201907/Media", className = "jp.yahooapis.im.v201907.media.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://im.yahooapis.jp/V201907/Media", className = "jp.yahooapis.im.v201907.media.GetResponse")
    public void get(@WebParam(name = "selector", targetNamespace = "http://im.yahooapis.jp/V201907/Media") MediaSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201907/Media", mode = WebParam.Mode.OUT) Holder<MediaPage> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201907/Media", mode = WebParam.Mode.OUT) Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://im.yahooapis.jp/V201907/Media", className = "jp.yahooapis.im.v201907.media.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://im.yahooapis.jp/V201907/Media", className = "jp.yahooapis.im.v201907.media.MutateResponse")
    public void mutate(@WebParam(name = "operations", targetNamespace = "http://im.yahooapis.jp/V201907/Media") MediaOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://im.yahooapis.jp/V201907/Media", mode = WebParam.Mode.OUT) Holder<MediaReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://im.yahooapis.jp/V201907/Media", mode = WebParam.Mode.OUT) Holder<List<Error>> error)
        throws ApiException
    ;

}
