
package jp.yahooapis.im.V5.BalanceService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BalanceServiceService", targetNamespace = "http://im.yahooapis.jp/V5", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V5.3/BalanceService?wsdl")
public class BalanceServiceService
    extends Service
{

    private final static URL BALANCESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BALANCESERVICESERVICE_EXCEPTION;
    private final static QName BALANCESERVICESERVICE_QNAME = new QName("http://im.yahooapis.jp/V5", "BalanceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V5.3/BalanceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BALANCESERVICESERVICE_WSDL_LOCATION = url;
        BALANCESERVICESERVICE_EXCEPTION = e;
    }

    public BalanceServiceService() {
        super(__getWsdlLocation(), BALANCESERVICESERVICE_QNAME);
    }

    public BalanceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BALANCESERVICESERVICE_QNAME, features);
    }

    public BalanceServiceService(URL wsdlLocation) {
        super(wsdlLocation, BALANCESERVICESERVICE_QNAME);
    }

    public BalanceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BALANCESERVICESERVICE_QNAME, features);
    }

    public BalanceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BalanceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BalanceServiceInterface
     */
    @WebEndpoint(name = "BalanceService")
    public BalanceServiceInterface getBalanceService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V5", "BalanceService"), BalanceServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BalanceServiceInterface
     */
    @WebEndpoint(name = "BalanceService")
    public BalanceServiceInterface getBalanceService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V5", "BalanceService"), BalanceServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BALANCESERVICESERVICE_EXCEPTION!= null) {
            throw BALANCESERVICESERVICE_EXCEPTION;
        }
        return BALANCESERVICESERVICE_WSDL_LOCATION;
    }

}
