
package jp.yahooapis.im.v201809.retargetingtag;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RetargetingTagService", targetNamespace = "http://im.yahooapis.jp/V201809/RetargetingTag", wsdlLocation = "https://sandbox.im.yahooapis.jp/services/V201809/RetargetingTagService?wsdl")
public class RetargetingTagService
    extends Service
{

    private final static URL RETARGETINGTAGSERVICE_WSDL_LOCATION;
    private final static WebServiceException RETARGETINGTAGSERVICE_EXCEPTION;
    private final static QName RETARGETINGTAGSERVICE_QNAME = new QName("http://im.yahooapis.jp/V201809/RetargetingTag", "RetargetingTagService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.im.yahooapis.jp/services/V201809/RetargetingTagService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RETARGETINGTAGSERVICE_WSDL_LOCATION = url;
        RETARGETINGTAGSERVICE_EXCEPTION = e;
    }

    public RetargetingTagService() {
        super(__getWsdlLocation(), RETARGETINGTAGSERVICE_QNAME);
    }

    public RetargetingTagService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RETARGETINGTAGSERVICE_QNAME, features);
    }

    public RetargetingTagService(URL wsdlLocation) {
        super(wsdlLocation, RETARGETINGTAGSERVICE_QNAME);
    }

    public RetargetingTagService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RETARGETINGTAGSERVICE_QNAME, features);
    }

    public RetargetingTagService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetargetingTagService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RetargetingTagServiceInterface
     */
    @WebEndpoint(name = "RetargetingTagService")
    public RetargetingTagServiceInterface getRetargetingTagService() {
        return super.getPort(new QName("http://im.yahooapis.jp/V201809/RetargetingTag", "RetargetingTagService"), RetargetingTagServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetargetingTagServiceInterface
     */
    @WebEndpoint(name = "RetargetingTagService")
    public RetargetingTagServiceInterface getRetargetingTagService(WebServiceFeature... features) {
        return super.getPort(new QName("http://im.yahooapis.jp/V201809/RetargetingTag", "RetargetingTagService"), RetargetingTagServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RETARGETINGTAGSERVICE_EXCEPTION!= null) {
            throw RETARGETINGTAGSERVICE_EXCEPTION;
        }
        return RETARGETINGTAGSERVICE_WSDL_LOCATION;
    }

}
